package menu

// Defaults is the built-in menu content (spec #90). Entries reference registry
// command ids; ids that are not registered yet (future roadmaps, blocked
// ledger) render disabled with their dependency hint until they land.
func Defaults() []Menu {
	return []Menu{
		{Title: "File", Items: []Item{
			{Title: "New Project…", Command: "project.new"},
			{Title: "New Scratch File", Command: "scratch.new"},
			{Title: "Open Scratch File…", Command: "scratch.list"},
			{Title: "Generate Test Data…", Command: "scratch.generate"},
			{Title: "Open File…", Command: "file.openPath"},
			{Title: "Save", Command: "editor.write"},
			{Title: "Save All", Command: "editor.saveAll"},
			{Title: "Close Tab", Command: "editor.closeTab"},
			{Title: "Reopen Closed Tab", Command: "editor.tab.reopenClosed"},
			{Title: "Switch Project", Command: "project.switch"},
			{Title: "Close Project", Command: "project.close"},
			{Title: "Clone Repository…", Command: "project.clone"},
		}},
		{Title: "Edit", Items: []Item{
			{Title: "Undo", Command: "editor.undo"},
			{Title: "Redo", Command: "editor.redo"},
			{Title: "Copy", Command: "editor.copy"},
			{Title: "Cut", Command: "editor.cut"},
			{Title: "Paste", Command: "editor.paste"},
			{Title: "Paste from History", Command: "editor.pasteFromHistory"},
			{Title: "Duplicate Line", Command: "editor.duplicateLine"},
			{Title: "Find in File", Command: "editor.find"},
		}},
		{Title: "View", Items: []Item{
			{Title: "Focus Explorer / Editor", Command: "explorer.toggle"},
			{Title: "Split View Right", Command: "editor.splitViewRight"},
			{Title: "Split View Down", Command: "editor.splitViewDown"},
			{Title: "Maximize Pane", Command: "pane.maximize"},
			{Title: "Zen Mode", Command: "view.zenMode"},
			{Title: "Hide All Tool Windows", Command: "window.hideAllTools"},
			{Title: "External Changes", Command: "watch.changeFeed"},
			{Title: "Treat Buffer as…", Command: "editor.setBufferLanguage"},
			{Title: "Materialize Buffer to File", Command: "editor.materializeBuffer"},
			{Title: "Export Screenshot (Pane)", Command: "view.exportScreenshot"},
			{Title: "Export Screenshot (Window)", Command: "view.exportWindowScreenshot"},
			{Title: "Performance HUD", Command: "perf.hud"},
			{Title: "Copy Performance Snapshot", Command: "perf.snapshot"},
		}},
		{Title: "Navigate", Items: []Item{
			{Title: "Go to File", Command: "project.goToFile"},
			{Title: "Recent Files", Command: "palette.recentFiles"},
			{Title: "Pinned Files", Command: "nav.pins"},
			{Title: "Bookmarks", Command: "nav.bookmarks"},
			{Title: "Toggle Bookmark", Command: "bookmark.toggle"},
			{Title: "Toggle Bookmark with Mnemonic", Command: "bookmark.toggleMnemonic"},
			{Title: "Edit Bookmark Note", Command: "bookmark.annotate"},
			{Title: "Next Bookmark", Command: "bookmark.next"},
			{Title: "Previous Bookmark", Command: "bookmark.previous"},
			{Title: "Go to Declaration", Command: "lsp.definition"},
			{Title: "Go to Super", Command: "lsp.goToSuper"},
			{Title: "Go to Implementations", Command: "lsp.implementations"},
			{Title: "Type Hierarchy", Command: "lsp.typeHierarchy"},
			{Title: "Back", Command: "nav.back"},
			{Title: "Forward", Command: "nav.forward"},
		}},
		{Title: "Run", Items: []Item{
			{Title: "Run File", Command: "run.file"},
			{Title: "Rerun Last", Command: "run.rerun"},
			{Title: "Run/Debug Configurations…", Command: "run.select"},
			{Title: "Run Task…", Command: "run.task"},
			{Title: "Promote Task to Run Configuration…", Command: "run.taskPromote"},
			{Title: "Run Test at Cursor", Command: "run.testAtCursor"},
			{Title: "Run Tests in File", Command: "run.testsInFile"},
			{Title: "Run HTTP Request", Command: "http.run"},
			{Title: "Toggle Breakpoint", Command: "debug.toggleBreakpoint"},
			{Title: "Breakpoints", Command: "debug.breakpoints"},
			{Title: "Debug File", Command: "debug.start"},
			{Title: "Debug Test at Cursor", Command: "debug.testAtCursor"},
			{Title: "Listen for PHP Debug Connections", Command: "debug.listen"},
			{Title: "Xdebug Doctor", Command: "debug.doctor"},
			{Title: "Step Over", Command: "debug.stepOver"},
			{Title: "Step Into", Command: "debug.stepInto"},
			{Title: "Step Out", Command: "debug.stepOut"},
			{Title: "Continue", Command: "debug.continue"},
			{Title: "Stop Debug Session", Command: "debug.stop"},
		}},
		{Title: "Tools", Items: []Item{
			{Title: "Problems", Command: "problems.toggle"},
			{Title: "Test Results", Command: "tests.toggle"},
			{Title: "GitHub Issues", Command: "issues.toggle"},
			{Title: "DOM Inspector", Command: "dom.toggle"},
			{Title: "Scratch Files", Command: "scratch.panel"},
			{Title: "Terminal", Command: "terminal.toggle"},
			{Title: "Popup Terminal", Command: "terminal.popup"},
			{Title: "New Terminal", Command: "terminal.new"},
			{Title: "New Terminal Tab", Command: "terminal.newTab"},
			{Title: "SSH Host…", Command: "terminal.ssh"},
			{Title: "Browse SSH Host (SFTP)…", Command: "remote.browse"},
			{Title: "Regex Tester…", Command: "tools.regexTester"},
			{Title: "jq Playground…", Command: "json.jqPlayground"},
			{Title: "jq Playground at Cursor Path…", Command: "json.jqPlaygroundAtPath"},
			{Title: "Saved jq Filters…", Command: "json.jqFilters"},
			{Title: "Rename Saved jq Filter…", Command: "json.jqRenameFilter"},
			{Title: "yq Playground…", Command: "yaml.yqPlayground"},
			{Title: "yq Playground at Cursor Path…", Command: "yaml.yqPlaygroundAtPath"},
			{Title: "Saved yq Filters…", Command: "yaml.yqFilters"},
			{Title: "Rename Saved yq Filter…", Command: "yaml.yqRenameFilter"},
			{Title: "Save Playground Filter…", Command: "json.jqSaveFilter"},
			{Title: "Toggle Full Query View", Command: "json.jqQueryView"},
			{Title: "Restart Language Servers", Command: "lsp.restart"},
			{Title: "LSP Doctor", Command: "lsp.doctor"},
			{Title: "Plugins", Command: "tools.plugins"},
		}},
		{Title: "Settings", Items: []Item{
			{Title: "Settings…", Command: "settings.open"},
			{Title: "Keymap Cheatsheet", Command: "palette.keymapHelp"},
		}},
		{Title: "Help", Items: []Item{
			{Title: "Commands & Shortcuts", Command: "palette.keymapHelp"},
			{Title: "Notification History", Command: "notifications.history"},
		}},
	}
}
