package openapi

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"ike/internal/httpfile"
)

// specIn copies a fixture spec into a temporary directory and returns its
// path — imports write next to the spec, so every case needs its own dir.
func specIn(t *testing.T, fixture string) string {
	t.Helper()
	data, err := os.ReadFile("testdata/" + fixture)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), fixture)
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

// read returns a file's content, failing the test when it is missing.
func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("expected %s to exist: %v", filepath.Base(path), err)
	}
	return string(data)
}

// TestImportFileWritesBesideSpec (#1939): the request file is named after the
// spec and lands in its directory, together with both environment skeletons.
func TestImportFileWritesBesideSpec(t *testing.T) {
	spec := specIn(t, "petstore.yaml")
	dir := filepath.Dir(spec)

	res, err := ImportFile(spec)
	if err != nil {
		t.Fatal(err)
	}
	if want := filepath.Join(dir, "petstore.http"); res.HTTPFile != want {
		t.Errorf("wrote %s, want %s", res.HTTPFile, want)
	}
	if res.Operations != 6 {
		t.Errorf("Operations = %d, want 6", res.Operations)
	}
	if res.EnvFile == "" || res.PrivateEnvFile == "" {
		t.Errorf("both environment skeletons must be created: %+v", res)
	}
	if len(res.MissingVars) != 0 {
		t.Errorf("a freshly written environment defines everything, got %v", res.MissingVars)
	}

	// The written file is a request file the client can read, and the
	// environment resolves every placeholder in it.
	f := httpfile.Parse(read(t, res.HTTPFile))
	if len(f.Errors) != 0 {
		t.Fatalf("written file does not parse: %v", f.Errors)
	}
	envs, err := httpfile.LoadEnvironments(dir)
	if err != nil {
		t.Fatal(err)
	}
	vars := &httpfile.Vars{File: f.VarMap(), Env: envs.Vars(EnvName)}
	for _, r := range f.Requests {
		if _, err := r.ResolveVars(vars); err != nil {
			t.Errorf("%s: %v", r.Key(), err)
		}
	}
}

// TestImportFileSummary (#1939): the one-line report names the file, the
// skeletons it wrote and what it had to leave out.
func TestImportFileSummary(t *testing.T) {
	res, err := ImportFile(specIn(t, "edge.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	sum := res.Summary()
	for _, want := range []string{"9 requests → edge.http", "http-client.env.json", "skipped ("} {
		if !strings.Contains(sum, want) {
			t.Errorf("summary %q does not mention %q", sum, want)
		}
	}
}

// TestImportFileKeepsExistingEnvironment (#1939): environment files hold the
// user's values, so an import never replaces them — it reports the variables
// they are missing instead.
func TestImportFileKeepsExistingEnvironment(t *testing.T) {
	spec := specIn(t, "petstore.yaml")
	dir := filepath.Dir(spec)
	existing := `{"prod": {"host": "https://petstore.example.com"}}`
	if err := os.WriteFile(filepath.Join(dir, httpfile.EnvFileName), []byte(existing), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := ImportFile(spec)
	if err != nil {
		t.Fatal(err)
	}
	if res.EnvFile != "" {
		t.Error("an existing http-client.env.json must be kept")
	}
	if got := read(t, filepath.Join(dir, httpfile.EnvFileName)); got != existing {
		t.Errorf("the existing environment was rewritten:\n%s", got)
	}
	if strings.Join(res.MissingVars, ",") != "X-Request-Id,limit,petId,status" {
		t.Errorf("MissingVars = %v", res.MissingVars)
	}
	if !strings.Contains(res.Summary(), "add X-Request-Id, limit, petId, status") {
		t.Errorf("the summary must name what to add: %s", res.Summary())
	}
}

// TestImportFileOverwriteRules (#1939): a request file the importer wrote is
// regenerated in place, a hand-written one of the same name stops the import.
func TestImportFileOverwriteRules(t *testing.T) {
	t.Run("regenerates its own output", func(t *testing.T) {
		spec := specIn(t, "petstore.yaml")
		first, err := ImportFile(spec)
		if err != nil {
			t.Fatal(err)
		}
		before := read(t, first.HTTPFile)
		if _, err := ImportFile(spec); err != nil {
			t.Fatalf("re-import must succeed: %v", err)
		}
		if after := read(t, first.HTTPFile); after != before {
			t.Error("re-importing the same spec must produce the same file")
		}
	})

	t.Run("refuses a hand-written file", func(t *testing.T) {
		spec := specIn(t, "petstore.yaml")
		target := filepath.Join(filepath.Dir(spec), "petstore.http")
		mine := "### my own request\nGET https://example.com/\n"
		if err := os.WriteFile(target, []byte(mine), 0o644); err != nil {
			t.Fatal(err)
		}
		_, err := ImportFile(spec)
		if err == nil {
			t.Fatal("want an error rather than a lost file")
		}
		if !strings.Contains(err.Error(), "was not generated by the importer") {
			t.Errorf("error = %q", err)
		}
		if got := read(t, target); got != mine {
			t.Error("the hand-written file must be untouched")
		}
	})
}

// TestImportFileErrors (#1939): an unreadable, unparseable or empty document
// fails with a message naming the file and the reason.
func TestImportFileErrors(t *testing.T) {
	dir := t.TempDir()
	empty := filepath.Join(dir, "empty.yaml")
	if err := os.WriteFile(empty, []byte("openapi: 3.0.0\ninfo: {title: none, version: '1'}\npaths: {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cases := []struct {
		name, path, want string
	}{
		{"missing file", filepath.Join(dir, "nope.yaml"), "nope.yaml"},
		{"swagger 2.0", specIn(t, "swagger2.json"), "Swagger 2.0 is not supported"},
		{"no operations", empty, "declares no operations"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ImportFile(tc.path)
			if err == nil {
				t.Fatal("want an error")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error = %q, want it to mention %q", err, tc.want)
			}
		})
	}
	// Nothing was written for the rejected documents.
	for _, name := range []string{"empty.http", httpfile.EnvFileName} {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			t.Errorf("%s must not be written for a rejected document", name)
		}
	}
}
