package openapi

// import.go is the file-level half of the OpenAPI import (#1939): read a spec
// from disk, generate the request file, and write it — plus the environment
// skeletons — next to the spec.
//
// Writing next to the spec (rather than opening an unsaved buffer) is the
// deliberate choice: the generated placeholders resolve from
// http-client.env.json, and the client looks for that file in the *request
// file's own directory. A buffer the user still has to place would resolve
// nothing until it is saved, and saving it somewhere else would leave the
// environment behind.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"ike/internal/httpfile"
)

// ImportResult reports what an import wrote and what it left alone.
type ImportResult struct {
	// HTTPFile is the path of the written request file.
	HTTPFile string
	// EnvFile and PrivateEnvFile name the environment skeletons that were
	// created; each is empty when the file already existed and was kept.
	EnvFile        string
	PrivateEnvFile string
	// MissingVars lists the variables the kept environment files do not
	// define — the placeholders that would fail to resolve on the first run.
	MissingVars []string
	// Operations counts the generated request blocks.
	Operations int
	// Skipped is everything the reader and the generator could not represent.
	Skipped []string
}

// Summary is the one-line report of an import.
func (r *ImportResult) Summary() string {
	out := fmt.Sprintf("%d requests → %s", r.Operations, filepath.Base(r.HTTPFile))
	var created []string
	for _, f := range []string{r.EnvFile, r.PrivateEnvFile} {
		if f != "" {
			created = append(created, filepath.Base(f))
		}
	}
	if len(created) > 0 {
		out += ", wrote " + strings.Join(created, " + ")
	}
	if len(r.MissingVars) > 0 {
		out += fmt.Sprintf("; add %s to the existing environment", strings.Join(r.MissingVars, ", "))
	}
	if s := SkipSummary(r.Skipped); s != "" {
		out += "; " + s
	}
	return out
}

// ImportFile reads the OpenAPI document at specPath and writes the request
// file beside it, named after the spec (`petstore.yaml` → `petstore.http`).
//
// An existing request file is only overwritten when it carries the generated
// header (GeneratedMarker) — a hand-written `.http` file of the same name
// stops the import with an error instead of being lost. The environment
// skeletons are written only when they do not exist yet: they hold the user's
// values, which an import has no business replacing.
func ImportFile(specPath string) (*ImportResult, error) {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return nil, err
	}
	return ImportDocument(data, filepath.Base(specPath), filepath.Dir(specPath))
}

// ImportDocument writes the request file for an already-read document into
// dir, named after specName (`petstore.yaml` → `petstore.http`). It is what
// ImportFile does once the bytes are in hand, and the seam the URL import
// (#2009) generates from: the dialog has already fetched and validated the
// document, so importing it must not fetch it a second time — a spec served
// dynamically could otherwise differ between the check and the import.
func ImportDocument(data []byte, specName, dir string) (*ImportResult, error) {
	specName = filepath.Base(specName)
	spec, err := Parse(data)
	if err != nil {
		return nil, fmt.Errorf("%s: %v", specName, err)
	}
	res := Generate(spec, Options{SpecName: specName})
	if res.Operations == 0 {
		return nil, fmt.Errorf("%s: the document declares no operations", specName)
	}

	base := strings.TrimSuffix(specName, filepath.Ext(specName))
	if base == "" {
		base = "openapi"
	}
	target := filepath.Join(dir, base+httpfile.Ext)
	if err := checkOverwrite(target); err != nil {
		return nil, err
	}
	if err := os.WriteFile(target, []byte(res.HTTP), 0o644); err != nil {
		return nil, err
	}

	out := &ImportResult{HTTPFile: target, Operations: res.Operations, Skipped: res.Skipped}
	envPath := filepath.Join(dir, httpfile.EnvFileName)
	privPath := filepath.Join(dir, httpfile.PrivateEnvFileName)
	if writeIfAbsent(envPath, res.Env) {
		out.EnvFile = envPath
	}
	if writeIfAbsent(privPath, res.PrivateEnv) {
		out.PrivateEnvFile = privPath
	}
	out.MissingVars = missingVars(dir, res.Vars)
	return out, nil
}

// checkOverwrite refuses to replace a request file the importer did not
// write. Reading the first line is enough: the marker opens it.
func checkOverwrite(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil // missing (or unreadable) — the write reports any real problem
	}
	first, _, _ := strings.Cut(string(data), "\n")
	if strings.HasPrefix(first, GeneratedMarker) {
		return nil
	}
	return fmt.Errorf("%s already exists and was not generated by the importer — move it aside first",
		filepath.Base(path))
}

// writeIfAbsent writes content unless the file already exists, reporting
// whether it created it.
func writeIfAbsent(path, content string) bool {
	if _, err := os.Stat(path); err == nil {
		return false
	}
	return os.WriteFile(path, []byte(content), 0o644) == nil
}

// missingVars names the generated variables no environment in dir defines —
// what the user has to add by hand when the import kept existing environment
// files. Every environment counts, since which one is selected is the user's
// choice at dispatch time.
func missingVars(dir string, vars []Var) []string {
	envs, err := httpfile.LoadEnvironments(dir)
	if err != nil || envs.Len() == 0 {
		return nil
	}
	defined := map[string]bool{}
	for _, name := range envs.Names() {
		for k := range envs.Vars(name) {
			defined[k] = true
		}
	}
	var out []string
	for _, v := range vars {
		if !defined[v.Name] {
			out = append(out, v.Name)
		}
	}
	sort.Strings(out)
	return out
}
