package graphql

import (
	"fmt"
	"strings"
)

// sdl.go renders a cached schema back as SDL — the form `http.graphqlSchema`
// opens in a scratch file (#2423). An introspection payload is a wall of JSON
// nobody reads; the SDL of the same schema is the document the API's own
// authors wrote, so "what can I ask this server?" is answered by scrolling it.
//
// Introspection meta types (`__Schema`, `__Type`, …) and the five built-in
// scalars are left out: they are the same in every schema and say nothing
// about this one.

// SDL renders the schema as a Schema Definition Language document.
func (s *Schema) SDL() string {
	if s == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Generated by IKE from a GraphQL introspection query.\n")
	b.WriteString(s.schemaBlock())
	for i := range s.Types {
		t := &s.Types[i]
		if strings.HasPrefix(t.Name, "__") || (t.Kind == KindScalar && builtinScalars[t.Name]) {
			continue
		}
		b.WriteString("\n")
		b.WriteString(t.sdl())
	}
	return b.String()
}

// schemaBlock names the operation roots. It is written even when they carry
// the conventional names, so the document states its entry points outright.
func (s *Schema) schemaBlock() string {
	var rows []string
	for _, r := range []struct{ op, name string }{
		{"query", s.QueryType},
		{"mutation", s.MutationType},
		{"subscription", s.SubscriptionType},
	} {
		if r.name != "" {
			rows = append(rows, fmt.Sprintf("  %s: %s", r.op, r.name))
		}
	}
	if len(rows) == 0 {
		return ""
	}
	return "\nschema {\n" + strings.Join(rows, "\n") + "\n}\n"
}

// sdl renders one type definition.
func (t *Type) sdl() string {
	var b strings.Builder
	b.WriteString(describe(t.Description, ""))
	switch t.Kind {
	case KindScalar:
		fmt.Fprintf(&b, "scalar %s\n", t.Name)
	case KindUnion:
		fmt.Fprintf(&b, "union %s = %s\n", t.Name, strings.Join(t.Possible, " | "))
	case KindEnum:
		fmt.Fprintf(&b, "enum %s {\n", t.Name)
		for _, v := range t.EnumValues {
			b.WriteString(describe(v.Description, "  "))
			fmt.Fprintf(&b, "  %s%s\n", v.Name, deprecated(v.Deprecated))
		}
		b.WriteString("}\n")
	case KindInputObject:
		fmt.Fprintf(&b, "input %s {\n", t.Name)
		for _, f := range t.InputFields {
			b.WriteString(describe(f.Description, "  "))
			fmt.Fprintf(&b, "  %s\n", f.sdl())
		}
		b.WriteString("}\n")
	default: // OBJECT, INTERFACE
		keyword := "type"
		if t.Kind == KindInterface {
			keyword = "interface"
		}
		fmt.Fprintf(&b, "%s %s", keyword, t.Name)
		if len(t.Interfaces) > 0 {
			fmt.Fprintf(&b, " implements %s", strings.Join(t.Interfaces, " & "))
		}
		b.WriteString(" {\n")
		for _, f := range t.Fields {
			b.WriteString(describe(f.Description, "  "))
			fmt.Fprintf(&b, "  %s%s: %s%s\n", f.Name, argList(f.Args), f.Type, deprecated(f.Deprecated))
		}
		b.WriteString("}\n")
	}
	return b.String()
}

// sdl renders one input value ("id: ID! = 1").
func (v InputValue) sdl() string {
	s := v.Name + ": " + v.Type
	if v.Default != "" {
		s += " = " + v.Default
	}
	return s
}

// argList renders a field's argument list, "" when it takes none.
func argList(args []InputValue) string {
	if len(args) == 0 {
		return ""
	}
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = a.sdl()
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// describe renders a description as an SDL block string, "" when there is
// none. Quotes inside are dropped rather than escaped: the block would end
// early, and a description is documentation, not data.
func describe(text, indent string) string {
	if text == "" {
		return ""
	}
	var b strings.Builder
	b.WriteString(indent + "\"\"\"\n")
	for _, line := range strings.Split(strings.ReplaceAll(text, `"""`, `'''`), "\n") {
		b.WriteString(indent + line + "\n")
	}
	b.WriteString(indent + "\"\"\"\n")
	return b.String()
}

func deprecated(is bool) string {
	if !is {
		return ""
	}
	return " @deprecated"
}
