// Package shotpng turns a rendered terminal frame — the ANSI string an IKE
// view produces — into a PNG image (#1634). The user documentation ships
// screenshots of real features, and generating them from the app itself keeps
// them honest: a shot is a frame the code actually rendered, regenerated by
// `go run ./cmd/shotgen` whenever the UI changes, not a photograph of someone's
// terminal.
//
// The frame is replayed through a VT emulator (the same one the integrated
// terminal uses), which flattens escape sequences into a grid of styled cells.
// Each cell is then painted: background rectangle, then the glyph — from the
// font, or drawn procedurally for box-drawing and block characters (box.go).
package shotpng

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
	"path/filepath"
	"strings"

	uv "github.com/charmbracelet/ultraviolet"
	"github.com/charmbracelet/x/vt"
	"golang.org/x/image/font"
	"golang.org/x/image/math/fixed"
)

// Options configures a render. Cols/Rows are the frame's terminal size; the
// frame is replayed into a screen of exactly that size.
type Options struct {
	Cols, Rows int
	// Fonts is the loaded font set; nil loads the platform default.
	Fonts *Fonts
	// Padding is the pixel margin around the grid.
	Padding int
	// Fg and Bg are the screen's default colours — what a cell with no colour
	// of its own gets. They mirror tea.View's ForegroundColor/BackgroundColor,
	// which is where IKE sets the theme's base colours.
	Fg, Bg color.Color
	// Region crops the shot to a rectangle in *cell* coordinates (max
	// exclusive). The zero value renders the whole frame.
	Region image.Rectangle
}

// Render replays frame into a cell grid and paints it into an image.
func Render(frame string, opt Options) (*image.RGBA, error) {
	if opt.Cols <= 0 || opt.Rows <= 0 {
		return nil, fmt.Errorf("shotpng: bad frame size %dx%d", opt.Cols, opt.Rows)
	}
	fonts := opt.Fonts
	if fonts == nil {
		var err error
		if fonts, err = LoadFonts(DefaultFontSpec(0)); err != nil {
			return nil, err
		}
	}
	region := opt.Region
	if region.Empty() {
		region = image.Rect(0, 0, opt.Cols, opt.Rows)
	}
	region = region.Intersect(image.Rect(0, 0, opt.Cols, opt.Rows))
	if region.Empty() {
		return nil, fmt.Errorf("shotpng: region outside the %dx%d frame", opt.Cols, opt.Rows)
	}

	em := vt.NewEmulator(opt.Cols, opt.Rows)
	// A VT needs carriage returns; a rendered view is joined with plain "\n".
	if _, err := em.WriteString(strings.ReplaceAll(frame, "\n", "\r\n")); err != nil {
		return nil, fmt.Errorf("shotpng: replaying the frame: %w", err)
	}

	defFg := toRGBA(opt.Fg, color.RGBA{0xd0, 0xd0, 0xd0, 0xff})
	defBg := toRGBA(opt.Bg, color.RGBA{0x00, 0x00, 0x00, 0xff})

	pad := opt.Padding
	img := image.NewRGBA(image.Rect(0, 0,
		2*pad+region.Dx()*fonts.CellW,
		2*pad+region.Dy()*fonts.CellH,
	))
	fill(img, img.Bounds(), defBg)

	for y := region.Min.Y; y < region.Max.Y; y++ {
		for x := region.Min.X; x < region.Max.X; x++ {
			cell := em.CellAt(x, y)
			if cell == nil {
				continue
			}
			rect := image.Rect(
				pad+(x-region.Min.X)*fonts.CellW,
				pad+(y-region.Min.Y)*fonts.CellH,
				pad+(x-region.Min.X+max(1, cell.Width))*fonts.CellW,
				pad+(y-region.Min.Y+1)*fonts.CellH,
			)
			drawCell(img, rect, cell, fonts, defFg, defBg)
		}
	}
	return img, nil
}

// drawCell paints one cell: background, glyph, then the line decorations.
func drawCell(img *image.RGBA, rect image.Rectangle, cell *uv.Cell, fonts *Fonts, defFg, defBg color.RGBA) {
	st := cell.Style
	fg := toRGBA(st.Fg, defFg)
	bg := toRGBA(st.Bg, defBg)
	if st.Attrs&uv.AttrReverse != 0 {
		fg, bg = bg, fg
	}
	if st.Attrs&uv.AttrFaint != 0 {
		fg = blend(bg, fg, 0.5)
	}
	fill(img, rect, bg)
	if st.Attrs&uv.AttrConceal != 0 {
		return
	}

	content := cell.Content
	if content != "" && content != " " {
		bold := st.Attrs&uv.AttrBold != 0
		italic := st.Attrs&uv.AttrItalic != 0
		runes := []rune(content)
		if len(runes) == 1 && drawCellRune(img, rect, runes[0], fg, bg) {
			// Painted procedurally (border or block character).
		} else {
			face, synth := fonts.faceFor(runes[0], bold, italic)
			drawGlyph(img, rect, content, face, fonts, fg, synth)
		}
	}

	if st.Underline != uv.UnderlineNone {
		ul := fg
		if st.UnderlineColor != nil {
			ul = toRGBA(st.UnderlineColor, fg)
		}
		t := max(1, fonts.CellH/16)
		y := rect.Min.Y + fonts.Ascent + t
		fill(img, image.Rect(rect.Min.X, y, rect.Max.X, y+t), ul)
	}
	if st.Attrs&uv.AttrStrikethrough != 0 {
		t := max(1, fonts.CellH/16)
		y := rect.Min.Y + fonts.Ascent - fonts.CellH/6
		fill(img, image.Rect(rect.Min.X, y, rect.Max.X, y+t), fg)
	}
}

// drawGlyph renders the cell's grapheme with the given face, clipped to the
// cell so a wide fallback glyph cannot bleed into its neighbour.
func drawGlyph(img *image.RGBA, rect image.Rectangle, content string, face *styledFace, fonts *Fonts, fg color.RGBA, synthBold bool) {
	// One extra column of slack: a few glyphs (italics especially) overhang
	// their advance, and clipping them at the cell edge looks worse than the
	// overlap does.
	clip := rect
	clip.Max.X = min(clip.Max.X+fonts.CellW/3, img.Bounds().Max.X)
	d := font.Drawer{
		Dst:  img.SubImage(clip).(*image.RGBA),
		Src:  image.NewUniform(fg),
		Face: face.face,
		Dot: fixed.Point26_6{
			X: fixed.I(rect.Min.X),
			Y: fixed.I(rect.Min.Y + fonts.Ascent),
		},
	}
	d.DrawString(content)
	if synthBold {
		d.Dot = fixed.Point26_6{
			X: fixed.I(rect.Min.X) + fixed.I(1)/2,
			Y: fixed.I(rect.Min.Y + fonts.Ascent),
		}
		d.DrawString(content)
	}
}

// toRGBA resolves any colour to opaque RGBA, falling back to def for nil.
// ANSI, 256-colour and true-colour values all implement color.Color with the
// xterm palette behind the indexed ones, so this is the only conversion needed.
func toRGBA(c, def color.Color) color.RGBA {
	if c == nil {
		return toRGBA(def, color.RGBA{})
	}
	r, g, b, a := c.RGBA()
	if a == 0 {
		return toRGBA(def, color.RGBA{})
	}
	return color.RGBA{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8), 0xff}
}

// Encode writes an image as PNG bytes.
func Encode(img image.Image) ([]byte, error) {
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// WriteFile encodes an image and writes it to path, creating the directory.
func WriteFile(path string, img image.Image) error {
	data, err := Encode(img)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
